config/routes.rb
Rails.application.routes.draw do
  root 'jokes#index'
  resources :jokes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joke.rb
class Joke < ApplicationRecord
  validates :joke, :comedian, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/funny_controller.rb
class FunnyController < ApplicationController
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController

  def index
    @joke = Joke.order("RANDOM()").first
  end

  def new
    @joke = Joke.new
  end

  def create
    Joke.create(joke_params)
    redirect_to root_path
  end

  def joke_params
    params.require(:joke).permit(:joke, :comedian)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/funny_helper.rb
module FunnyHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/jokes/index.html.erb
<br /><br />
<div class="title text-center col-10 offset-1">
<h1>Got Jokes?</h1>
</div>
<br /><br />
<div class="booyah-box col-10 offset-1 text-center">
  <h1><%= @joke.joke %></h1><br />
  <br />
  <h2>- <i><%= @joke.comedian %></i></h2>
  <br />
  <%= link_to "Tell another one!", root_path, class: 'another-one' %>
</div>
<br /><br />
<div class="text-center col-10 offset-1 new-joke">
  <%= link_to 'Add your best joke here!', new_joke_path %>

app/views/jokes/new.html.erb
<div class="booyah-box col-10 offset-1 text-center">
  <h1>Got a Joke? I want to hear it.</h1>
  <br /><br />
  <%= simple_form_for @joke do |f| %>
    <h2><%= f.input :joke %></h2>
    <br />
    <h2><%= f.input :comedian %></h2>
    <br /><br />
    <%= f.submit 'Submit', class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>